# Generated by Django 5.2.7 on 2025-11-06 03:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.CharField(blank=True, max_length=100, null=True)),
                ('rev', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_num', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, help_text='The date this sequence was created.', null=True, verbose_name='Date Test Sequence Created:')),
                ('date_edited', models.DateField(blank=True, default=datetime.date.today, help_text='The date this sequence was last edited.', null=True, verbose_name='Date Test Sequence Edited:')),
                ('pcb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sequences', to='pcbs.pcb')),
            ],
        ),
    ]
