# Generated by Django 5.2.7 on 2025-11-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcb',
            name='image',
        ),
    ]
