# Generated by Django 5.2.7 on 2025-11-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0003_pcb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
