# Generated by Django 5.2.7 on 2025-11-13 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbs', '0004_alter_pcb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serialnumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn_num', models.IntegerField(blank=True, null=True, unique=True)),
                ('date_iss', models.DateField(auto_now_add=True)),
                ('pcb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='pcbs.pcb')),
            ],
        ),
    ]
